version: 2.0

jobs:
  prechecking:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Bundle install dependencies
      - run: cd GDesign
      - save_cache:
           key: v1-repo-xfy123
           paths:
             - ./../circleci-demo-workflows  
  build:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    steps:
      - restore_cache:
          keys:
            - v1-repo-xfy123
      # Bundle install dependencies
      - run: |
             cd GDesign  &&
             pwd  &&
             ls -al &&
             make clean &&
             make all
      - save_cache:
           key: v1-repo-xfy123
           paths:
             - ./../circleci-demo-workflows
  deploy:
    machine:
       enable: true
    working_directory: ~/circleci-demo-workflows
    steps:
      - restore_cache:
          keys:
            - v1-repo-xfy123
      - run: |             
             cd GDesign &&
             echo "Installing ..."
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prechecking
      - build:
          requires:
            - prechecking
      - deploy:
          requires:
            - build
