version: 2.0
jobs:

  #=======prebuild========# 
  #  Clone code from git hub, Running format-code, license, spelling check
  prebuild:
    docker:
      - image: bingyuliu/sample_gdesign:0.2.1
    working_directory: ~/ColorfullTime-Bingyu
    steps:
      - checkout
      # Build, Test and Install
      - run:
          name: Prebuild
          command: |
             echo "prebuild..." &&
             pwd &&
             ls -al &&
             echo "=============="
             ls -al &&
             echo "Prebuild Done!" 
      - save_cache:
           key: gdesign-sourceCode-cache
           paths:
             - ./../ColorfullTime-Bingyu        

  #========Build-Test-Install==========# 
  build-test-install-simulate-debug:
    docker:
      - image: bingyuliu/sample_gdesign:0.2.1
    working_directory: ~/ColorfullTime-Bingyu
    steps:
      - restore_cache:
          keys:
            - gdesign-sourceCode-cache
      # Build, Test and Install
      - run: 
          name: BuildSimuateDebug
          command: |
            pwd &&
            ls ./.circleci -al &&
            ./.circleci/external "BuildSimuateDebug"
      - run: 
          name: TestSimuateDebug
          command: |          
            echo "Testing..." &&
            echo "Testing Done!"
      - run: 
          name: InstallSimuateDebug
          command: |
            pwd &&
            ./.circleci/external "InstallSimuateDebug" &&
            echo " Installation Done!"
      - save_cache:
           key: gdesign-sourceCode-cache-build-simulate-debug
           paths:
             - ./../ColorfullTime-Bingyu  
             


workflows:
  version: 2
  build-test-install:
    jobs:
      - prebuild
      #  prebuild-->build-simulate-debug
      - build-test-install-simulate-debug:
          requires:
            - prebuild
      
