version: 2.0
jobs:

  #=======prebuild========# 
  #  Clone code from git hub, Running format-code, license, spelling check
  prebuild:
    docker:
      - image: bingyuliu/sample_gdesign:0.2.1
    working_directory: ~/ColorfullTime-Bingyu
    steps:
      - checkout
      # Build, Test and Install
      - run:
          name: Prebuild
          command: |
             echo "prebuild..." &&
             pwd &&
             ls -al &&
             echo "Prebuild Done!" 
      - save_cache:
           key: gdesign-sourceCode-cache
           paths:
             - ./../ColorfullTime-Bingyu        

  #========Build-Test-Install==========# 
  build-test-install-simulate-debug:
    docker:
      - image: bingyuliu/sample_gdesign:0.2.1
    working_directory: ~/ColorfullTime-Bingyu
    steps:
      - checkout
      # Build, Test and Install
      - run: 
          name: BuildSimuateDebug
          command: |
             apt-get install -y sudo &&
             pwd &&
             ls -al &&
             ls ./.circleci -al && 
             sudo sh ./script/buildtestinstall "BuildSimuateDebug"
      - run: 
          name: TestSimuateDebug
          command: |          
             echo "Testing..." &&
             echo "Testing Done!"
      - run: 
          name: InstallSimuateDebug
          command: |
             pwd &&
             sudo sh ./.circleci/externalscript/buildtestinstall "InstallSimuateDebug" &&
             echo " Installation Done!"
             
workflows:
  version: 2
  build-test-install:
    jobs:
      - prebuild
      #  prebuild-->build-simulate-debug
      - build-test-install-simulate-debug:
          requires:
            - prebuild
      
